"""Add mushroom_photos table

Revision ID: 9a2a4445c635
Revises: 26f38fa32335
Create Date: 2025-06-09 21:00:40.423098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2a4445c635'
down_revision: Union[str, None] = '26f38fa32335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mushroom_photos_mushroom_id'), 'mushroom_photos', ['mushroom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mushroom_photos_mushroom_id'), table_name='mushroom_photos')
    # ### end Alembic commands ###
